### ISSUE TITLE
[Bug] TrustLines with negative balances don't show up in app anymore

### ISSUE THREAD

**Issue by nixer89** [XRPL-Labs/XUMM-Issue-Tracker#192]
**Describe the bug**
TrustLines with a negative balance are not visibile in the app anymore. This is the case for an account which issued an IOU. The receiver account has the positive IOU balance but the issuer account does not have the trust line with the negative balance.

As example:
Testnet account:
https://test.bithomp.com/explorer/r3K1TgPvTPkWZR2Lhawpvv9YR7yYuqSXBp

**Expected behavior**
also TrustLines with a negative balance are shown

**Screenshots**
![IMG_1043](https://user-images.githubusercontent.com/25486793/82978575-35f81780-9fe5-11ea-97e4-45a79de94b25.PNG)
![IMG_1045](https://user-images.githubusercontent.com/25486793/82978616-47412400-9fe5-11ea-9474-999d9d4d6777.JPG)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 0.5.0.1

What device are you running XUMM on?

* Manufacturer: Apple
* Model: iPhone SE
* OS version: 13.x
* Platforms
  * [x] iOS
  * [ ] Android

### Additional context
Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by N3TC4T** [comment]
As I realised they are incoming TrustLines, we don't show incoming TrustLines anymore.

**Comment by WietseWind** [comment]
@N3TC4T Correct, but this is an obligation. A randomly incoming Trust Line should be ignored, except if I explicitly decided to issue and send funds over that incoming trust line, because I'm the issuer and I am willing to have an obligation.

You can check account obligations with (see the `obligations.<currency code>` response object)
```
{
  "command": "gateway_balances",
  "account": "rPEpPeRd6bp6tHxSVyNGVNiSaZK2KSsc68",
  "strict": true,
  "hotwallet": ["rPEpPeRd6bp6tHxSVyNGVNiSaZK2KSsc68"]
}
```
![image](https://user-images.githubusercontent.com/4756161/83881227-9c490c80-a740-11ea-95b0-7eb61e0cf564.png)
