### ISSUE TITLE
[Improvement/requirement V1] Add disclaimers during onboarding.

### ISSUE THREAD

**Issue by Wietse-Livingroom** [XRPL-Labs/XUMM-Issue-Tracker#300]
- Per screen
- Countdown timer to force people to read, timer is visible and the accept button is visible but disabled, until the timer ends.

### XUMM is non custodial
> XUMM is a non custodial wallet, meaning your funds aren't in XUMM custody, but 'live' on the XRP ledger.
> Only you can access your funds with your account secrets, as generated by XUMM or imported into XUMM.
> This means XUMM and the XUMM team cannot access and cannot recover your funds if you make a mistake or lose your secret keys.
  `[ I understand ]`

### Keep your secrets safe
> Only you, using your account secret(s) can access your funds.
> You and you alone are responsible of keeping them safe, offline.
> Write down your backups at multiple offline locations.
  `[ I understand, I will keep my secrets safe and offline ]`

### Transactions are permanent
>  XUMM cannot revert transactions, or recover funds if you make a mistake.
> Transactions are instant and irreversible.
  `[ I'm responsible for keeping my keys and funds safe ]`

### Your funds 'live' on the XRP ledger
> XUMM is an XRP ledger client application.
> This means your XRP does not reside <IN XUMM> but  <ON THE XRP Ledger>.
> Transactions sent and received are sent and received live on/by the XRP ledger.
  `[ I understand, my funds are registered on the XRP ledger, not inside XUMM ]`

### NEVER share your secret
> XUMM and the XUMM support department WILL NEVER ask for your secret
> If someone does, or asks you to enter your secret somewhere, you are being scammed.
> Please do contact us with as much information that you have about the incident.
  `[ I understand, I will never give my secret sto anyone and never enter it elsewhere ]`

### When you change your phone
> When you get another phone (new / replacement), for security reasons, XUMM will ask you to import all your accounts using the account secrets again.
  `[ I understand, I will keep my secrets safe, offline, so I can re-enter them if I get a new phone ]`

### Questions & support
> If you have questions, you can read FAQ's and ask questions at https://support.xumm.app.
> This is THE ONLY trustworthy channel for XUMM support.
  `[ I understand, I will only trust answers from the XUMM support team at https://support.xumm.app ]`

### Terms & Conditions
> XUMM is a product by XRPL Labs. Please read the XRPL Labs Terms of Service, and continue only if you agree with them.
    `-- INCLUDE (existing) WEBVIEW --` https://xumm.app/app/webviews/tos-privacy
  `[ I agree with the Terms ]`

**Comment by WietseWind** [comment]
@NetScr1be @alloyxrp
Rough draft, for XUMM V1 later this month, the Beta label will be removed. I feel that, during onboarding, we should show sequence of disclaimers, for users to read and accept.

Any suggestions/comments/..?

**Comment by alloyxrp** [comment]
XUMM is non custodial -> XUMM is a non custodial wallet
keeping them safe, offline, back upped. -> keeping them safe, offline, with backups.
you are being scammed. - > you are being scammed. Please do contact us with as much information about the incident.

**Comment by NetScr1be** [comment]
Some notes;


White space (AKA negative space) matters as much as the words. It's the
frame that carries the words. The changes below include intentional use of
white space.


One idea per paragraph or the ideas get lost.


Generally, Double-quotes are for repeating full sentences and paragraphs.
Single quotes for terms and phrases. Usage varies from region to region.


-------------


XUMM is non-custodial, meaning your funds aren't in XUMM custody, but
'live' on the XRP ledger.

Only you can access your funds with your account secrets, as generated by
XUMM or imported into XUMM.

XUMM and the XUMM team cannot access and cannot recover your funds if you
make a mistake or lose your secret keys.

[ I understand]


-------------


Only you, using your account secret(s) can access your funds, and you are
responsible for keeping them safe, offline and backed up.


XUMM cannot revert transactions, or recover funds if you make a mistake.

[ I understand.

I will keep my secrets safe and offline.

I am wholly and solely responsible for keeping my keys and funds safe ]


-------------


XUMM is an XRP ledger client application.

Your XRP does not reside IN XUMM but ON THE XRP Ledger.

Transactions are sent and received are live on the XRP ledger.

[ I understand, my funds are registered on the XRP ledger, not inside XUMM ]


-------------


XUMM and the XUMM support department WILL NEVER ask for your seed, secret,
passphrase or for you to send XRP.

If someone does, or asks you to enter your secret somewhere, you are being
scammed.

[ I understand, I will never give my secret to anyone and never enter it
elsewhere ]


-------------


When you get another phone (new / replacement), for security reasons, XUMM
wil ask you to import all your accounts using the account secrets again.

Xumm will return 'Invalid Authentication' if used after restoring from
backup.

[ I understand, I will keep my secrets safe, offline, so I can re-enter
them if I get a new phone ]


-------------


If you have questions, you can read FAQ's and ask questions at:
https://support.xumm.app.

THE ONLY trustworthy channels for XUMM support are listed at:
https://support.xumm.app/hc/en-us/articles/360018136280-Official-XUMM-communication-channels

[ I understand, I will only trust anwers from the XUMM support team at
https://support.xumm.app ]


-------------
