### ISSUE TITLE
[Improvement] Batch signing

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#352]
Suggestion: for e.g. salary payouts, batch vendor payout, batch tipping, etc.

API/SDK:
- Create multiple payloads (as possible today)
- (new) Create a "payload batch", 'grouping' an array of pending payloads
- Send the user to the batch payload UUID

XUMM:
Instead of showing one payload with payload details to sign:
- Shows a list 
- Requires all payloads in the list to be opened (reviewed) and closed again
- Gets signing permission (Passphrase / FaceID / fingerprint)
- Signs and submits them (automatically) one by one

Exception:
- Tangem cards require tapping the card for every stage in the sign list.

**Comment by flyfoxuk** [comment]
Very useful addition for the use case of tipping multiple users at the same time, in the same tweet.  Batch processing the signing of tips to multiple recipients.

**Comment by flyfoxuk** [comment]
New use case for this: onboarding new users to a particular token ecosystem with a fresh unactivated wallet in XUMM - one batch transaction set including:

- "Payment" of base reserve + trustline reserve + a little spending money (say, 25.1 XRP), plus;
- "TrustSet" for a given token, plus;
- "Payment" of bonus starter amount of token currency (optional)

Presumably a waiting time between each type of event would need to happen so that confirmation of reserve payment is received from the ledger before attempting TrustSet, and subsequently the bonus payment.  Perhaps deal with this by looking at the sequence of events specified and waiting for prior ones to satisfy if the next one is a different type or a different currency involved from previous and on the same address.

**Comment by WietseWind** [comment]
Closing as more clarity is provided here: #425
