### ISSUE TITLE
[Improvement] Improve Ticket functions

### ISSUE THREAD

**Issue by WietseWind** [XRPL-Labs/XUMM-Issue-Tracker#379]
The XRPL recently added support for Tickets. XUMM can use a couple of improvements when it comes to the way it deals with tickets.

Every ticket created with a `TicketCreate` transaction becomes a ledger object, to be found with an `account_objects` command. E.g. filtered on Tickets (type):
```
{
  "command": "account_objects",
  "account": "rwietsevLFg8XSmG3bEZzFein1g8RBqWDZ",
  "type": "ticket"
}
```

When one opens the ["Explain balance" tab, tickets are correctly displayed](https://nlz9qke.dlvr.cloud/IMG_1820.PNG) (each their individual object, each claiming a 2 XRP (owner count) reserve.

Right now, it's impossible for people to see their owned tickets, and the ticket numbers still available. 

### Suggestion 1 - Show existing tickets (account_objects)

- [x] Tickets are basically "Planned items". It makes sense for them to show up on the Events - Planned tab. There are two options to display them here
  - Option 1: simple: just one line per ticket, displaying the fact that they are a ticket and their number. When tapped, I guess the matching TicketCreate transaction could show.
  - Option 2: advanced (preferred): if at least one ticket exists, show one Ticket item, e.g. `12 tickets`, and when tapped, show a list with all the available ticket numbers.

### Suggestion 2 - Show created tickets

- [x] When a `TicketCreate` transaction is tapped, it only shows there are X amount of tickets created: it would be useful to add a list below with the ticket numbers created.

### Suggestion 3 - (Bugfix) - show the right amount of reserve

- [x] Right now every transaction in the Event list that added to the reserve shows the [amount of one owner count on the Event details page. A `TicketCreate` transaction with e.g. 10 tickets to create locks up 10 * 2 = 20 XRP, not 2](https://nlz9qke.dlvr.cloud/IMG_1822.PNG).

**Comment by N3TC4T** [comment]
Explain Balance now shows the accounts object grouped instead of showing every object in separate line

<img src="https://user-images.githubusercontent.com/6250203/165921796-ed6134e1-52d9-4c1c-8285-75baaedc8b11.png" width="200">

Tickets are now shown as open in Events -> Planned tab

<img src="https://user-images.githubusercontent.com/6250203/165922038-4025a6cf-02da-4ad1-946d-fd2d3df8ece0.png" width="200">


Tickets now can be cancelled from within Details screen

<img src="https://user-images.githubusercontent.com/6250203/165922038-4025a6cf-02da-4ad1-946d-fd2d3df8ece0.png" width="200">
![Simulator Screen Shot - iPhone 12 Pro Max - 2022-04-29 at 11 47 23](https://user-images.githubusercontent.com/6250203/165922312-1bdd3982-405d-4979-b190-a7abcf13809a.png)

**Comment by WietseWind** [comment]
Very nice, as always :D 

For the default translation (first screenshot) we should go with `Tickets` (without the `'`)
